version: '3'
services:
  app:
    #app_goの中にあるDockerfileの読み込み
    build: ./todo
    container_name: "app"
    tty: true
    #ホストのディレクトリをコンテナにマウント
    volumes:
      - ./todo:/go/src/todo
#  envoy:
#    build:
#  front:
#    build:
